build_packages_task:
  only_if: ${CIRRUS_TAG} == ''

  matrix:
    - name: 'Linux x86_64'
      container:
        image: centos:centos7
        cpu: 4
        memory: 8G
    - name: 'Linux aarch64'
      arm_container:
        image: centos:centos7
        cpu: 4
        memory: 8G

  clone_script: |
    yum update -y && yum upgrade -y
    yum install -y git

    git clone -b "${CIRRUS_BRANCH}" https://github.com/adonis0147/devel-env
    cd devel-env
    git fetch --tags

  prepare_script: |
    cd devel-env

    while read -r tag; do
      url="https://github.com/adonis0147/devel-env/releases/download/${tag}/install_toolchain_$(uname -m).sh"
      if curl --silent --head --fail -L "${url}" -o /dev/null; then
        break
      fi
    done < <(git tag -l | tac)

    echo "Download the toolchain from ${url}"
    curl -L "${url}" -o devel/scripts/install_toolchain.sh
    chmod a+x devel/scripts/install_toolchain.sh

    devel/downloads/download_packages.sh

  script: |
    yum install -y xz file make gettext texinfo

    cd devel-env/devel/scripts
    DEVEL_HOME_PATH=/opt/devel bash install.sh
