build_packages_task:
  only_if: ${CIRRUS_TAG} == ''

  container:
    image: centos:centos7
    cpu: 4
    memory: 8G

  clone_script: |
    curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo
    yum update -y && yum upgrade -y
    yum install -y git

    git clone -b "${CIRRUS_BRANCH}" https://github.com/adonis0147/devel-env
    cd devel-env
    git fetch --tags

  prepare_script: |
    cd devel-env

    latest_tag="$(git tag -l | tail -n 1)"
    curl -L "https://github.com/adonis0147/devel-env/releases/download/${latest_tag}/install_toolchain.sh" \
      -o devel/scripts/install_toolchain.sh
    chmod a+x devel/scripts/install_toolchain.sh

    devel/downloads/download_packages.sh

  script: |
    yum install -y xz file make gettext texinfo

    export DEVEL_HOME_PATH=/opt/devel

    mkdir -p "${DEVEL_HOME_PATH}/opt/cmake"
    curl -L https://github.com/Kitware/CMake/releases/download/v3.25.2/cmake-3.25.2-linux-x86_64.tar.gz \
      -o /tmp/cmake-3.25.2-linux-x86_64.tar.gz
    tar -zxvf /tmp/cmake-3.25.2-linux-x86_64.tar.gz -C "${DEVEL_HOME_PATH}/opt/cmake" --strip-components=1
    mkdir -p "${DEVEL_HOME_PATH}/bin"
    ln -snf "${DEVEL_HOME_PATH}/opt/cmake/bin/cmake" "${DEVEL_HOME_PATH}/bin/"

    cd devel-env/devel/scripts
    bash install.sh
