build_packages_task:
  only_if: ${CIRRUS_TAG} == ''
  timeout_in: 120m

  compute_engine_instance:
    platform: linux
    cpu: 4
    memory: 8G
    image_project: cirrus-images
    matrix:
      - name: 'Linux x86_64'
        image: family/docker-builder
      - name: 'Linux aarch64'
        image: family/docker-builder-arm64
        architecture: arm64

  clone_script: |
    git clone -b "${CIRRUS_BRANCH}" https://github.com/adonis0147/devel-env
    cd devel-env
    git fetch --tags

  prepare_script: |
    cd devel-env

    while read -r tag; do
      url="https://github.com/adonis0147/devel-env/releases/download/${tag}/install_toolchain_$(uname -m).sh"
      if curl --silent --head --fail -L "${url}" -o /dev/null; then
        break
      fi
    done < <(git tag --sort=creatordate | tac)

    echo "Download the toolchain from ${url}"
    curl -L "${url}" -o devel/scripts/install_toolchain.sh
    chmod a+x devel/scripts/install_toolchain.sh

    devel/downloads/download_packages.sh

    # Don't install llvm
    sed -i '/function install_packages/,/^}/ s/install_llvm//' devel/scripts/install.sh

    if [[ "$(uname -m)" != 'x86_64' ]]; then
      # Don't install neovim
      sed -i '/function install_packages/,/^}/ s/install_neovim//' devel/scripts/install.sh
    fi

    # Don't install zsh
    sed -i '/function install_packages/,/^}/ s/install_zsh//' devel/scripts/install.sh

  script: |
    cat >Dockerfile <<EOF
    FROM centos:centos7
    RUN yum install -y xz file make gettext texinfo

    RUN mkdir /devel-env
    WORKDIR /devel-env

    CMD ["/bin/bash"]
    EOF

    docker build -t packages .
    docker run --rm --mount=type=bind,source="$(pwd)/devel-env",target=/devel-env packages \
      bash -c 'cd devel/scripts; bash install.sh'
