#cloud-config

users:
  - default

system_info:
  default_user:
    name: centos
    passwd: $6$rounds=4096$DVM84PuZSIQUvQSa$4GAYurcjoJq/d7l.QmZgNANjUPVwvpyN.FINJPpSdyEuSjYD6cGhAU4ktFcrznp5x3Syilwls2HF//I4brWaX/
    lock_passwd: False
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD4xHQP5NRgSSEAtgrUgFoba7HZZpg8VzehkBZ+FQLTiABaPXK/SDvlT5Sf3o9WofCDEh+MjYku+wfJdAs0o+WptmmqguAmIwj5mikaXSyAMd+KPmJBBeptuMo0r4pN3KTIwbwqAczfn/2dAjMr9kXN7ApQbr4iB2SMm40M6Nfi5HxZa8IPaM1UVUankxbtTulNA5vH3KsTwbv52nheQGtrFbwG6FOnVo3DO564JbWIJ1I14VCogbXNFODdOAnq7XtVrAADJ5j/FAxff8NNbJM12b2Mx4aDDzm12IC13rkCIzdU5H3iJJhNVAIbF4KUNeVLK4cnY3D8TaJhiop4wM6fvMlX5vzbRia7qL8EOI+QCl1kZarMAKYUtZFaZIkZ5GGv657qVjAVlQhaCGTCmyL7F9asz26dlJgV7ITMnTtW/m7clFlL+pE2Fb1ivpJLS3NNiRYaeJnongmeDinm//lERj31wFZOOa2+Ukvf8gPEHkx8s778xizk6XvJVsjiZ6U= centos@centos

runcmd:
  - sed -i -e 's|mirrorlist=|#mirrorlist=|' -e 's|#baseurl=http://mirror.centos.org/centos/\$releasever|baseurl=https://vault.centos.org/7.9.2009|' /etc/yum.repos.d/CentOS-Base.repo
