name: Release

on:
  push:

jobs:
  Build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Build toolchain
        run: |
          mkdir -p output
          docker build -t toolchain toolchain
          docker run --rm --mount type=bind,source="$(pwd)/output",target=/output toolchain
          mv output/install_toolchain.sh "output/install_toolchain_${{ matrix.arch }}.sh"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: toolchain-${{ matrix.arch }}
          path: output/install_toolchain_${{ matrix.arch }}.sh
