name: ShellCheck

on:
  push:

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          format: tty
